# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_back(object):
    def setupUi(self, back):
        back.setObjectName("back")
        back.resize(261, 421)
        back.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.seven = QtWidgets.QPushButton(back)
        self.seven.setGeometry(QtCore.QRect(10, 170, 61, 61))
        self.seven.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.seven.setObjectName("seven")
        self.eight = QtWidgets.QPushButton(back)
        self.eight.setGeometry(QtCore.QRect(70, 170, 61, 61))
        self.eight.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.eight.setObjectName("eight")
        self.nine = QtWidgets.QPushButton(back)
        self.nine.setGeometry(QtCore.QRect(130, 170, 61, 61))
        self.nine.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.nine.setObjectName("nine")
        self.four = QtWidgets.QPushButton(back)
        self.four.setGeometry(QtCore.QRect(10, 230, 61, 61))
        self.four.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(back)
        self.five.setGeometry(QtCore.QRect(70, 230, 61, 61))
        self.five.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.five.setObjectName("five")
        self.six = QtWidgets.QPushButton(back)
        self.six.setGeometry(QtCore.QRect(130, 230, 61, 61))
        self.six.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.six.setObjectName("six")
        self.one = QtWidgets.QPushButton(back)
        self.one.setGeometry(QtCore.QRect(10, 290, 61, 61))
        self.one.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(back)
        self.two.setGeometry(QtCore.QRect(70, 290, 61, 61))
        self.two.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(back)
        self.three.setGeometry(QtCore.QRect(130, 290, 61, 61))
        self.three.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.three.setObjectName("three")
        self.zero = QtWidgets.QPushButton(back)
        self.zero.setGeometry(QtCore.QRect(10, 350, 121, 61))
        self.zero.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255)\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(235, 235, 235);\n"
"color: rgb(27, 27, 27)\n"
"}")
        self.zero.setObjectName("zero")
        self.add = QtWidgets.QPushButton(back)
        self.add.setGeometry(QtCore.QRect(190, 110, 61, 61))
        self.add.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.add.setObjectName("add")
        self.div = QtWidgets.QPushButton(back)
        self.div.setGeometry(QtCore.QRect(190, 290, 61, 61))
        self.div.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.div.setObjectName("div")
        self.sub = QtWidgets.QPushButton(back)
        self.sub.setGeometry(QtCore.QRect(190, 170, 61, 61))
        self.sub.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.sub.setObjectName("sub")
        self.mul = QtWidgets.QPushButton(back)
        self.mul.setGeometry(QtCore.QRect(190, 230, 61, 61))
        self.mul.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.mul.setObjectName("mul")
        self.equal = QtWidgets.QPushButton(back)
        self.equal.setGeometry(QtCore.QRect(130, 110, 61, 61))
        self.equal.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.equal.setObjectName("equal")
        self.c = QtWidgets.QPushButton(back)
        self.c.setGeometry(QtCore.QRect(10, 110, 121, 61))
        self.c.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.c.setObjectName("c")
        self.openpar = QtWidgets.QPushButton(back)
        self.openpar.setGeometry(QtCore.QRect(130, 350, 61, 61))
        self.openpar.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.openpar.setObjectName("openpar")
        self.result = QtWidgets.QLabel(back)
        self.result.setGeometry(QtCore.QRect(10, 10, 241, 101))
        self.result.setStyleSheet("background-color: rgb(234, 234, 234);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.closepar = QtWidgets.QPushButton(back)
        self.closepar.setGeometry(QtCore.QRect(190, 350, 61, 61))
        self.closepar.setStyleSheet("QPushButton{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(213, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255)\n"
"}")
        self.closepar.setObjectName("closepar")

        self.retranslateUi(back)
        QtCore.QMetaObject.connectSlotsByName(back)

    def retranslateUi(self, back):
        _translate = QtCore.QCoreApplication.translate
        back.setWindowTitle(_translate("back", "My Calculator"))
        self.seven.setText(_translate("back", "7"))
        self.eight.setText(_translate("back", "8"))
        self.nine.setText(_translate("back", "9"))
        self.four.setText(_translate("back", "4"))
        self.five.setText(_translate("back", "5"))
        self.six.setText(_translate("back", "6"))
        self.one.setText(_translate("back", "1"))
        self.two.setText(_translate("back", "2"))
        self.three.setText(_translate("back", "3"))
        self.zero.setText(_translate("back", "0"))
        self.add.setText(_translate("back", "+"))
        self.div.setText(_translate("back", "/"))
        self.sub.setText(_translate("back", "-"))
        self.mul.setText(_translate("back", "*"))
        self.equal.setText(_translate("back", "="))
        self.c.setText(_translate("back", "C"))
        self.openpar.setText(_translate("back", "("))
        self.result.setText(_translate("back", " "))
        self.closepar.setText(_translate("back", ")"))
